# Generated by Django 4.1.7 on 2023-04-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenguages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travels',
            new_name='Lenguages',
        ),
    ]
